[tool.poetry]
name = "django-reactive"
version = "0.0.2"
description = "Django JSON form field on steroids using react-json-schema-form"
authors = ["Artem Kolesnikov <tyomo4ka@gmail.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/tyomo4ka/django-reactive"
repository = "https://github.com/tyomo4ka/django-reactive"
documentation = "https://github.com/tyomo4ka/django-reactive"
keywords = ["django",
            "postgres",
            "json",
            "jsonschema",
            "react"]


[tool.poetry.dependencies]
python = ">=3.6,<4"
jsonschema = "^3.2.0"
psycopg2-binary = "^2.8.4"


[tool.poetry.dev-dependencies]
bump2version = "^1.0.0"
coverage = "^5.0.3"
mock = "^3.0.5"
flake8 = "^3.7.9"
tox = "^3.14.3"
codecov = "^2.0.15"
Django = "^3.0.2"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
